""" https://leetcode.com/problems/find-the-difference
leetCode 389. Find the Difference.
Easy

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""

from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        orig_counts = Counter(s)
        
        for c in t:
            if orig_counts[c] == 0:
                return c
            orig_counts[c] -= 1
            
        # should not end up here
        return ""
